name: Flask Application

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements ]; then pip install -r requirements; fi
    - name: Flask test
      run: |
        export FLASK_APP=main.py
        flask test
